# Generated by Django 3.2.5 on 2023-06-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_auto_20230612_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Retired', 'Retired')], default='Draft', max_length=10),
        ),
    ]
