# Generated by Django 3.2.5 on 2023-07-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_dashboards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboards',
        ),
    ]
