# Generated by Django 3.2.5 on 2023-07-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_delete_dashboards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Retired', 'Retired')], default='Draft', max_length=50)),
                ('dashboard_type', models.CharField(choices=[('Custom', 'Custom'), ('External', 'External')], default='Custom', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(verbose_name='Published Date')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('dashboards', models.ManyToManyField(to='dashboards.Dashboards')),
            ],
        ),
    ]
