# Generated by Django 3.2.5 on 2023-10-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_dashboards_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
