# Generated by Django 3.2.5 on 2023-12-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_dashboards_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboards',
            name='image',
            field=models.ImageField(blank=True, default='grafana_logo_icon_171048.png', null=True, upload_to=''),
        ),
    ]
