version: "3"
services: 

  observability:
    image: joagonzalez/obvservability-dashboards:1.0.6-apache2
    build: 
      context: .
      dockerfile: ./build/apache/Dockerfile
    ports:
      - '8001:80'