# Generated by Django 3.2.5 on 2023-12-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuarios',
            name='email',
            field=models.CharField(default='johndoe@gmail.com', max_length=100),
        ),
    ]
