# Generated by Django 3.2.5 on 2023-11-27 22:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('mail', models.EmailField(blank=True, max_length=80, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(blank=True, verbose_name=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('date', models.DateField(blank=True, verbose_name=datetime.datetime.now)),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacto.consulta')),
            ],
        ),
    ]
