# Generated by Django 3.2.5 on 2023-11-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='answer_state',
            field=models.CharField(choices=[('Contestada', 'Contestada'), ('No Contestada', 'No Contestada'), ('En Proceso', 'En Proceso')], default='No Contestada', max_length=15, null=True),
        ),
    ]
