# Generated by Django 3.2.5 on 2023-11-28 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_consulta_answer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
